package chain

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The shared hash-chain vectors in tests/conformance are generated by
// the TypeScript producer. This suite must reproduce every chainHash and
// rootHash from the raw events alone, and must reject the unsorted
// vector, or a chain sealed by the producer will not replay here.

type chainVector struct {
	Name     string            `json:"name"`
	Events   []json.RawMessage `json:"events"`
	Expected *struct {
		ChainHashes []string `json:"chainHashes"`
		RootHash    string   `json:"rootHash"`
	} `json:"expected"`
	ExpectedError string `json:"expectedError"`
}

func TestHashChainConformance(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("..", "..", "..", "tests", "conformance", "hash-chain-vectors.json"))
	if err != nil {
		t.Fatalf("read vectors: %v", err)
	}
	var doc struct {
		Vectors []chainVector `json:"vectors"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("decode vectors: %v", err)
	}
	for _, v := range doc.Vectors {
		v := v
		t.Run(v.Name, func(t *testing.T) {
			dir := t.TempDir()
			// The vector file is pretty-printed; events.jsonl is one object per line.
			var lines []string
			for _, e := range v.Events {
				var compact bytes.Buffer
				if err := json.Compact(&compact, e); err != nil {
					t.Fatal(err)
				}
				lines = append(lines, compact.String())
			}
			if err := os.WriteFile(filepath.Join(dir, "events.jsonl"), []byte(strings.Join(lines, "\n")+"\n"), 0o600); err != nil {
				t.Fatal(err)
			}
			res, err := ReplayChain(dir)
			if v.ExpectedError != "" {
				if err == nil || !strings.Contains(err.Error(), v.ExpectedError) {
					t.Fatalf("expected error containing %q, got %v", v.ExpectedError, err)
				}
				return
			}
			if err != nil {
				t.Fatalf("ReplayChain: %v", err)
			}
			if len(res.PayloadMismatches) != 0 {
				t.Fatalf("payload mismatches: %+v", res.PayloadMismatches)
			}
			if res.RootHash != v.Expected.RootHash {
				t.Errorf("rootHash = %s, want %s", res.RootHash, v.Expected.RootHash)
			}
			if res.NumericMonoNs != 0 {
				t.Errorf("vectors use string monoNs; replay counted %d numeric", res.NumericMonoNs)
			}
			// Re-run with the expected chainHash values present so the
			// per-event comparison path is exercised too.
			var withHashes []string
			for i, e := range v.Events {
				var obj map[string]interface{}
				if err := json.Unmarshal(e, &obj); err != nil {
					t.Fatal(err)
				}
				obj["chainHash"] = v.Expected.ChainHashes[i]
				b, _ := json.Marshal(obj)
				withHashes = append(withHashes, string(b))
			}
			if err := os.WriteFile(filepath.Join(dir, "events.jsonl"), []byte(strings.Join(withHashes, "\n")+"\n"), 0o600); err != nil {
				t.Fatal(err)
			}
			res2, err := ReplayChain(dir)
			if err != nil {
				t.Fatal(err)
			}
			if len(res2.HashMismatches) != 0 {
				t.Errorf("chainHash mismatches against expected vector values: %+v", res2.HashMismatches)
			}
		})
	}
}

func TestMonoNsValueForms(t *testing.T) {
	cases := []struct {
		raw      string
		want     int64
		isString bool
		wantErr  bool
	}{
		{`"0"`, 0, true, false},
		{`"9007199254740993"`, 9007199254740993, true, false},
		{`"9223372036854775807"`, 9223372036854775807, true, false},
		{`"9223372036854775808"`, 0, true, true},
		{`"007"`, 0, true, true},
		{`"-1"`, 0, true, true},
		{`"abc"`, 0, true, true},
		{`12`, 12, false, false},
		{`-3`, 0, false, true},
		{`1.5`, 0, false, true},
		{`null`, 0, false, true},
	}
	for _, c := range cases {
		got, isString, err := MonoNsValue(json.RawMessage(c.raw))
		if (err != nil) != c.wantErr {
			t.Errorf("%s: err=%v, wantErr=%v", c.raw, err, c.wantErr)
			continue
		}
		if err == nil && (got != c.want || isString != c.isString) {
			t.Errorf("%s: got (%d, %v), want (%d, %v)", c.raw, got, isString, c.want, c.isString)
		}
	}
}

// TestNumericMonoNsStillReplaysSchema2 keeps the v2 wire form working:
// a number is hashed as a number, matching what v2 producers signed.
func TestNumericMonoNsStillReplaysSchema2(t *testing.T) {
	dir := t.TempDir()
	payloadHash, _ := recomputePayloadHash([]byte(`{"text":"v2"}`))
	line := `{"id":"01JCONF0000000000000000001","wallTs":"2025-05-18T15:30:00.000Z","monoNs":7,"sessionId":"s","agentId":"claude-code","parentEventId":null,"type":"prompt","payload":{"text":"v2"},"payloadHash":"` + payloadHash + `"}`
	if err := os.WriteFile(filepath.Join(dir, "events.jsonl"), []byte(line+"\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	res, err := ReplayChain(dir)
	if err != nil {
		t.Fatal(err)
	}
	if res.NumericMonoNs != 1 {
		t.Fatalf("expected the numeric form to be counted, got %d", res.NumericMonoNs)
	}
}
