// packages/narrative/src/rule-902.ts
//
// FRE 902(13) and 902(14) self-authenticating certification template.
//
// BUILD_PLAN.md §6 Phase 4:
//   "Optional 902(13)/(14) certification template signed by
//    the bundle producer."
//
// This template generates a certification statement that a human
// bundle producer can sign, asserting that the bundle meets the
// requirements of Federal Rules of Evidence 902(13) (certified
// electronic records) and 902(14) (certified data copied from
// an electronic device).
//
// IMPORTANT: DEPOSE does not make admissibility claims. This template
// is a starting point for a human certifier. The certifier must
// review and attest to the truthfulness of each statement.
//
// See docs/legal-considerations.md for the full FRE analysis.

// ── Certification template data ────────────────────────────────────

export interface Rule902CertData {
  /** Bundle ID (from manifest) */
  bundleId: string;
  /** Production timestamp (from manifest) */
  producedAt: string;
  /** Root hash of the evidence chain */
  rootHash: string;
  /** Signature scheme used (e.g., "ed25519") */
  signatureScheme: string;
  /** RFC 3161 TSA that timestamped the bundle */
  timestampAuthority: string;
  /** Timestamp generation time */
  timestampGenTime: string;
  /** Number of events in the bundle */
  eventCount: number;
  /** Number of destructive operations */
  destructiveOpCount: number;
  /** Number of coverage gaps */
  gapCount: number;
  /** Certifier name (human who signs) */
  certifierName: string;
  /** Certifier title/role */
  certifierTitle: string;
  /** Certification date */
  certificationDate: string;
  /** Jurisdiction (optional) */
  jurisdiction?: string;
}

// ── Manifest extract type (avoids circular dep with @depose/bundle) ─

export interface ManifestExtract {
  bundleId: string;
  producedAt: string;
  rootHash: string;
  signatures: Array<{ scheme: string }>;
  timestamps: Array<{ tsa: string; timestamp: string }>;
  counts: {
    events: number;
    destructiveOperations: number;
    gaps: number;
  };
}

// ── Certification renderer ──────────────────────────────────────────

/**
 * Render a FRE 902(13)/(14) certification statement.
 *
 * This is a TEMPLATE, not a legal opinion. The certifier must
 * review each statement for accuracy before signing.
 */
export function renderRule902Cert(data: Rule902CertData): string {
  const lines: string[] = [];

  lines.push('CERTIFICATION PURSUANT TO FED. R. EVID. 902(13) AND 902(14)');
  lines.push('═══════════════════════════════════════════════════════════════');
  lines.push('');
  lines.push(`I, ${data.certifierName}, ${data.certifierTitle}, hereby certify:`);
  lines.push('');
  lines.push('1. BUNDLE IDENTIFICATION');
  lines.push('   I have personally reviewed the DEPOSE evidence bundle identified as:');
  lines.push(`   Bundle ID: ${data.bundleId}`);
  lines.push(`   Produced: ${data.producedAt} UTC`);
  lines.push(`   Root Hash: ${data.rootHash}`);
  lines.push(`   Events: ${data.eventCount} (${data.destructiveOpCount} destructive, ${data.gapCount} gaps)`);
  lines.push('');
  lines.push('2. FRE 902(13) — CERTIFIED RECORDS GENERATED BY AN ELECTRONIC PROCESS');
  lines.push('   The above-described bundle was generated by an electronic process');
  lines.push('   (the DEPOSE toolchain) that produces an accurate result when');
  lines.push('   operating as intended. Specifically:');
  lines.push('');
  lines.push('   a. The events in this bundle were captured by software that records');
  lines.push('      AI agent actions as they occur, without human intervention in the');
  lines.push('      recording process.');
  lines.push('');
  lines.push('   b. The events are linked by a cryptographic hash chain (IRONROOT');
  lines.push('      construction): each event\'s chain hash incorporates the previous');
  lines.push('      event\'s chain hash, making any single-event alteration detectable.');
  lines.push('');
  lines.push('   c. The bundle manifest is signed with an Ed25519 key pair, and the');
  lines.push(`   signature scheme is: ${data.signatureScheme}.`);
  lines.push('');
  lines.push('   d. An independent RFC 3161 Timestamp Authority has attested that this');
  lines.push(`   bundle existed at ${data.timestampGenTime} UTC. TSA: ${data.timestampAuthority}.`);
  lines.push('');
  lines.push('3. FRE 902(14) — CERTIFIED DATA COPIED FROM AN ELECTRONIC DEVICE');
  lines.push('   The data in this bundle was copied from the computing device(s) on');
  lines.push('   which the recorded AI agent session occurred. The copy process');
  lines.push('   preserves the integrity of the data through:');
  lines.push('');
  lines.push('   a. Hash-verified copy: each file and event in the bundle carries a');
  lines.push('      SHA-256 digest; the verifier recomputes and compares these digests.');
  lines.push('');
  lines.push('   b. Chain of integrity: the root hash in the manifest is the terminal');
  lines.push('      hash of the chain over all events; any alteration to any event');
  lines.push('      changes the root hash and invalidates the signature.');
  lines.push('');
  lines.push('4. GAPS AND LIMITATIONS (DISCLOSED, NOT HIDDEN)');
  lines.push(`   This bundle contains ${data.gapCount} coverage gap(s). Gaps indicate events`);
  lines.push('   where pre-execution capture was not available for a tool result.');
  lines.push('   Each gap is recorded as a "gap" event in the timeline with a reason');
  lines.push('   and affected event IDs. Gaps are disclosed to support honest');
  lines.push('   evaluation, not to undermine it.');
  lines.push('');
  lines.push('5. EXCLUDED CONTENT');
  lines.push('   The file "commentary.md" (if present) is AI-GENERATED COMMENTARY');
  lines.push('   that is explicitly excluded from the signed content. It is not');
  lines.push('   part of the evidentiary record. Modifying commentary.md does not');
  lines.push('   affect bundle validity.');
  lines.push('');
  lines.push('6. VERIFICATION');
  lines.push('   Any person can verify this bundle using the open-source "depose-verify"');
  lines.push('   binary. Verification confirms hash chain integrity, signature');
  lines.push('   validity, RFC 3161 timestamp consistency, and artifact hash');
  lines.push('   matching. The verifier source code is available for independent audit.');
  lines.push('');
  lines.push('═══════════════════════════════════════════════════════════════');
  lines.push('');
  lines.push(`Certified by: ${data.certifierName}`);
  lines.push(`Title: ${data.certifierTitle}`);
  lines.push(`Date: ${data.certificationDate}`);
  if (data.jurisdiction) {
    lines.push(`Jurisdiction: ${data.jurisdiction}`);
  }
  lines.push('');
  lines.push('_______________________________');
  lines.push('Signature');
  lines.push('');
  lines.push('NOTICE: This certification is a template provided by the DEPOSE toolchain.');
  lines.push('It does not constitute a legal opinion or guarantee of admissibility.');
  lines.push('The certifier is responsible for the truthfulness of each statement above.');
  lines.push('Admission of evidence is always subject to judicial discretion.');

  return lines.join('\n');
}

// ── Build cert data from manifest extract ───────────────────────────

/**
 * Build Rule902CertData from a bundle manifest extract and certifier info.
 * The certifier must still review and sign the resulting document.
 */
export function buildCertDataFromManifest(
  manifest: ManifestExtract,
  certifier: { name: string; title: string; date: string; jurisdiction?: string }
): Rule902CertData {
  const tsAuthority = manifest.timestamps.length > 0
    ? manifest.timestamps[0]!.tsa
    : 'N/A';
  const tsTime = manifest.timestamps.length > 0
    ? manifest.timestamps[0]!.timestamp
    : 'N/A';

  return {
    bundleId: manifest.bundleId,
    producedAt: manifest.producedAt,
    rootHash: manifest.rootHash,
    signatureScheme: manifest.signatures.length > 0
      ? manifest.signatures[0]!.scheme
      : 'none',
    timestampAuthority: tsAuthority,
    timestampGenTime: tsTime,
    eventCount: manifest.counts.events,
    destructiveOpCount: manifest.counts.destructiveOperations,
    gapCount: manifest.counts.gaps,
    certifierName: certifier.name,
    certifierTitle: certifier.title,
    certificationDate: certifier.date,
    jurisdiction: certifier.jurisdiction,
  };
}