package cmd

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// The shared commitment vectors are generated by the TypeScript producer;
// the verifier must reproduce every hash and open the event vector.
func TestCommitmentConformance(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("..", "..", "..", "tests", "conformance", "commitment-vectors.json"))
	if err != nil {
		t.Fatalf("read vectors: %v", err)
	}
	var doc struct {
		Vectors []struct {
			Name     string          `json:"name"`
			Path     string          `json:"path"`
			Value    json.RawMessage `json:"value"`
			Salt     string          `json:"salt"`
			Expected string          `json:"expected"`
		} `json:"vectors"`
		EventVector struct {
			CommittedPayload json.RawMessage     `json:"committedPayload"`
			Openings         []commitmentOpening `json:"openings"`
		} `json:"eventVector"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatal(err)
	}
	for _, v := range doc.Vectors {
		got, err := computeCommitment(v.Salt, v.Path, v.Value)
		if err != nil {
			t.Errorf("%s: %v", v.Name, err)
			continue
		}
		if got != v.Expected {
			t.Errorf("%s: got %s want %s", v.Name, got, v.Expected)
		}
	}

	ev := doc.EventVector
	ids := []string{"01JCONF0000000000000000001"}
	payloads := []json.RawMessage{ev.CommittedPayload}
	report := openAll(ids, payloads, ev.Openings, true)
	if len(report.problems) != 0 {
		t.Fatalf("event vector must open cleanly: %v", report.problems)
	}
	if report.opened != 2 || report.placeholders != 2 {
		t.Errorf("opened=%d placeholders=%d, want 2 and 2", report.opened, report.placeholders)
	}

	wrongSalt := append([]commitmentOpening{}, ev.Openings...)
	wrongSalt[0].Salt = "ff" + wrongSalt[0].Salt[2:]
	if r := openAll(ids, payloads, wrongSalt, true); len(r.problems) == 0 {
		t.Error("a wrong salt must not open")
	}
	if r := openAll(ids, payloads, ev.Openings[:1], true); len(r.problems) == 0 {
		t.Error("a placeholder without an opening must be reported in a full bundle")
	}
	if r := openAll(ids, payloads, ev.Openings[:1], false); len(r.problems) != 0 {
		t.Error("a disclosure may leave placeholders unopened")
	}
}
